# Generated by Django 5.0.3 on 2024-03-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.IntegerField()),
                ('a', models.IntegerField()),
                ('o', models.IntegerField()),
                ('e', models.IntegerField()),
                ('n', models.IntegerField()),
            ],
        ),
    ]
