# Generated by Django 5.0.3 on 2024-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbigfive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
