# Generated by Django 4.2.11 on 2024-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbigfive', '0002_userscore_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='user',
            new_name='user_1',
        ),
    ]
